safe: true
lsi: false
pygments: true
paginate: 10
auto: true
markdown: redcarpet

permalink: /:categories/:year/:title
url: http://joanparsons.github.io/abfabdecoratingblog
baseurl: /abfabdecoratingblog

name: "Absolutely Fabulous Decorating | Creating beautiful, functional spaces"
description: "Creating beautiful, functional spaces"

prose:
  # rooturl: '_posts'
  siteurl: 'http://joanparsons.github.io/abfabdecoratingblog'
  media: 'images'
  relativeLinks: 'http://joanparsons.github.io/abfabdecoratingblog/links.jsonp'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose category"
          options:
            - name: "Blog"
              value: "blog"
            - name: "Portfolio"
              value: "portfolio"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Plants"
              value: "plants"
            - name: "Seasonal"
              value: "seasonal"
            - name: "Summer"
              value: "summer"
            - name: "Fall"
              value: "fall"
            - name: "Did you know?"
              value: 'did-you-know'
            - name: "Curtains"
              value: "curtains"
            - name: "Caramel"
              value: "caramel"
            - name: "Colour"
              value: "colour"
            - name: "Exterior"
              value: "exterior"
            - name: "Fabric"
              value: "fabric"
            - name: "Furniture"
              value: "furniture"
            - name: "Interior"
              value: "interior"
            - name: "Lighting"
              value: "lighting"
            - name: "Staging"
              value: "staging"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
