safe: true
lsi: false
pygments: true
paginate: 10
auto: true
markdown: redcarpet
permalink: /blog/:title
name: "Absolutely Fabulous Decorating | Creating beautiful, functional spaces"
description: "Creating beautiful, functional spaces"
url: http://www.abfabdecorating.com
